/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Chat: typeof import('./src/components/chat/Chat.vue')['default']
    copy: typeof import('./src/components/base/Popover copy.vue')['default']
    CreatePost: typeof import('./src/components/post/CreatePost.vue')['default']
    CreateUser: typeof import('./src/components/comList/CreateUser.vue')['default']
    FirstSlot: typeof import('./src/components/SlotApi/FirstSlot.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ImgUpload: typeof import('./src/components/ImgUpload.vue')['default']
    Index: typeof import('./src/components/Index.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Logout: typeof import('./src/components/Logout.vue')['default']
    ModifyUser: typeof import('./src/components/comList/ModifyUser.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    Popover: typeof import('./src/components/base/Popover.vue')['default']
    Popover3: typeof import('./src/components/base/Popover3.vue')['default']
    Post: typeof import('./src/components/post/Post.vue')['default']
    PostContent: typeof import('./src/components/post/PostContent.vue')['default']
    PostList: typeof import('./src/components/post/PostList.vue')['default']
    ReactIveApi: typeof import('./src/components/reactive/ReactIveApi.vue')['default']
    RefFirst: typeof import('./src/components/compostion/RefFirst.vue')['default']
    RenderEvent: typeof import('./src/components/reactive/RenderEvent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUp: typeof import('./src/components/SignUp.vue')['default']
    Swipper: typeof import('./src/components/Swipper.vue')['default']
    SwipperOne: typeof import('./src/components/SwipperOne.vue')['default']
    Tips: typeof import('./src/components/Tips.vue')['default']
    UserList: typeof import('./src/components/comList/UserList.vue')['default']
    UserPostList: typeof import('./src/components/user/UserPostList.vue')['default']
    VirtualScroll: typeof import('./src/components/post/VirtualScroll.vue')['default']
    WatchUse: typeof import('./src/components/compostion/WatchUse.vue')['default']
  }
}
